name: Java CI with Maven

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3
      - name: Configura o JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Compila o projeto com Maven
        run: mvn -B compile --file pom.xml

  build-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
    needs: build-dev
    steps:
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configura o JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Testa o projeto com Maven
        run: mvn -B test --file pom.xml

  build-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: build-hmg
    steps:
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3
      - name: Configura o JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: Empacota o projeto com Maven
        run: mvn -B package --file pom.xml -DskipTests
      - name: Crie uma pasta temporária de downloads de artefatos
        run: mkdir staging
      - name: Copia os artefatos a serem publicados na pasta temporária
        run: cp target/*jar-with-dependencies.jar staging
      - name: Usa Upload Artifact do GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
